ekf_localization_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.2
    two_d_mode: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    odom0: /cartographer/odometry
    odom0_config: [true, true, true,
                   true, true, true,
                   true, true, true,
                   true, true, true,
                   false, false, false]

    odom1: /orbslam3/odom
    odom1_config: [true, true, true,
                   true, true, true,
                   true, true, true,
                   true, true, true,
                   false, false, false]

    imu0: /camera/imu
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  true, true, true,
                  false, false, false]
    imu0_differential: false
